[project]
name = "replik8"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bcrypt>=5.0.0",
    "jinja2>=3.1.6",
    "sqlite-utils>=4.2.1",
]

[dependency-groups]
dev = [
    "debugpy>=1.8.21",
    "pytest>=9.1.1",
    "ty>=0.0.80",
    "watchfiles>=1.2.0",
]

[build-system]
requires = ["uv_build>=0.12.13,<0.13"]
build-backend = "uv_build"

[project.scripts]
replik8 = "replik8:main"
web_assets = "web_assets:main"

[tool.pytest.ini_options]
pythonpath = ["./src"]
