[project]
name = "replik8"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bcrypt>=5.0.0",
    "jinja2>=3.1.6",
    "sqlite-utils>=4.2.1",
]

[dependency-groups]
dev = [
    "debugpy>=1.8.21",
    "pytest>=9.1.1",
    "pytest-playwright>=0.9.0",
    "ty>=0.0.80",
    "watchfiles>=1.2.0",
]

[build-system]
requires = ["uv_build>=0.12.13,<0.13"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["replik8", "tracker", "web_assets", "web_server"]

[project.scripts]
replik8 = "replik8:main"
web_assets = "web_assets:main"
web_server = "web_server:main"
shared_utils = "shared_utils:main"
tracker = "tracker:main"

